# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(Dialog)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleLineEdit = QtWidgets.QLineEdit(Dialog)
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.titleLineEdit)
        self.roastLabel = QtWidgets.QLabel(Dialog)
        self.roastLabel.setObjectName("roastLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.roastLabel)
        self.roastComboBox = QtWidgets.QComboBox(Dialog)
        self.roastComboBox.setObjectName("roastComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.roastComboBox)
        self.groundLabel = QtWidgets.QLabel(Dialog)
        self.groundLabel.setObjectName("groundLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.groundLabel)
        self.groundCheckBox = QtWidgets.QCheckBox(Dialog)
        self.groundCheckBox.setObjectName("groundCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.groundCheckBox)
        self.tasteLabel = QtWidgets.QLabel(Dialog)
        self.tasteLabel.setObjectName("tasteLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tasteLabel)
        self.tasteLineEdit = QtWidgets.QLineEdit(Dialog)
        self.tasteLineEdit.setObjectName("tasteLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tasteLineEdit)
        self.priceLabel = QtWidgets.QLabel(Dialog)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.priceDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.priceDoubleSpinBox.setMaximum(200000000.0)
        self.priceDoubleSpinBox.setObjectName("priceDoubleSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.priceDoubleSpinBox)
        self.volumeLabel = QtWidgets.QLabel(Dialog)
        self.volumeLabel.setObjectName("volumeLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.volumeLabel)
        self.volumeSpinBox = QtWidgets.QSpinBox(Dialog)
        self.volumeSpinBox.setMinimum(1)
        self.volumeSpinBox.setMaximum(1000000)
        self.volumeSpinBox.setObjectName("volumeSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.volumeSpinBox)
        self.idLabel = QtWidgets.QLabel(Dialog)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.idLineEdit = QtWidgets.QLineEdit(Dialog)
        self.idLineEdit.setEnabled(False)
        self.idLineEdit.setObjectName("idLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleLabel.setText(_translate("Dialog", "Title"))
        self.roastLabel.setText(_translate("Dialog", "Roast"))
        self.groundLabel.setText(_translate("Dialog", "Ground"))
        self.tasteLabel.setText(_translate("Dialog", "Taste"))
        self.priceLabel.setText(_translate("Dialog", "Price, rub."))
        self.volumeLabel.setText(_translate("Dialog", "Volume, g"))
        self.idLabel.setText(_translate("Dialog", "ID:"))
        self.pushButton.setText(_translate("Dialog", "Save"))
